//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InsCate
    {
        public int ID { get; set; }
        [Display(Name = "項目代碼")]
        public string InsID { get; set; }
        [Display(Name = "項目名稱")]
        public string InsName { get; set; }
        [Display(Name = "加項/減項")]
        public string PosOrNeg { get; set; }
    }
}
