//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManpowerDBEntities : DbContext
    {
        public ManpowerDBEntities()
            : base("name=ManpowerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpInsurance> EmpInsurance { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<OwnerBuilding> OwnerBuilding { get; set; }
        public virtual DbSet<OwnerPayment> OwnerPayment { get; set; }
        public virtual DbSet<OwnerPayWork> OwnerPayWork { get; set; }
        public virtual DbSet<WorkCategory> WorkCategory { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkList> WorkList { get; set; }

        public System.Data.Entity.DbSet<Manpower_MVC.ViewModels.ViewWorkList> ViewWorkLists { get; set; }

        public System.Data.Entity.DbSet<Manpower_MVC.ViewModels.ViewWorker> ViewWorkers { get; set; }
    }
}
