//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerPayWork
    {
        public int ID { get; set; }
        public int SalaryDay { get; set; }
        public int OvertimeHr { get; set; }
        public int OverOvertimeHr { get; set; }
        public int WorkCareID { get; set; }
        public int PayID { get; set; }
    }
}
