//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkList
    {
        public int ID { get; set; }
        [Display(Name = "流水編號")]
        public string SerialNum { get; set; }
        [Display(Name = "單號")]
        public string SingleNum { get; set; }
        [Display(Name = "建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime CreateDate { get; set; }
        [Display(Name = "工地")]
        public string BuildName { get; set; }
        [Display(Name = "連絡人")]
        public string ConPerson { get; set; }
        [Display(Name = "業主")]
        public int OwnerID { get; set; }
    }
}
