//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkCategory
    {
        public int ID { get; set; }
        [DisplayName("代碼")]
        [Required]
        public string WorkCareID { get; set; }
        [DisplayName("工作職稱")]
        [Required]
        public string WorkCareName { get; set; }
        [DisplayName("日薪")]
        [Required]
        public int Salary { get; set; }
        [DisplayName("加班時薪")]
        [Required]
        public int OvertimeSal { get; set; }
        [DisplayName("超時時薪")]
        [Required]
        public int OverOvertimeSal { get; set; }
        [DisplayName("備註")]
        public string Remark { get; set; }
    }
}
