//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manpower_MVC.REST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Owner
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Display(Name = "代碼")]
        public string OwnerID { get; set; }
        [Display(Name = "名稱")]
        public string OwnerName { get; set; }
        [Display(Name = "電話")]
        public string Tel { get; set; }
        [Display(Name = "電話")]
        public string Tel2 { get; set; }
        [Display(Name = "連絡人")]
        public string ConPerson { get; set; }
        [Display(Name = "手機")]
        public string ConPersonPhone { get; set; }
        [Display(Name = "電話")]
        public string ConPersonTel { get; set; }
        [Display(Name = "統一編號")]
        public string UnifiedNum { get; set; }
        [Display(Name = "地址")]
        public string Address { get; set; }
    }
}
